name: sctranslation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h77fa898_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libsqlite=3.48.0=hee588c1_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.1=h7b32b05_0
  - pip=25.0=pyh8b19718_0
  - python=3.12.8=h9e4cc4f_1_cpython
  - python_abi=3.12=7_cp312
  - readline=8.2=h8228510_1
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2025a=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - altgraph==0.17.4
      - antlr4-python3-runtime==4.13.2
      - asgiref==3.9.0
      - astor==0.8.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - blake3==1.0.5
      - cachetools==6.1.0
      - cbor2==5.7.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.2.1
      - coloredlogs==15.0.1
      - compressed-tensors==0.10.2
      - contourpy==1.3.1
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - datasets==4.0.0
      - deepspeed==0.17.4
      - depyf==0.19.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - django==5.2.4
      - dnspython==2.7.0
      - docopt==0.6.2
      - einops==0.8.1
      - email-validator==2.2.0
      - fastapi==0.116.1
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.1.5
      - fastrlock==0.8.3
      - filelock==3.17.0
      - flatbuffers==25.2.10
      - fonttools==4.55.8
      - frozenlist==1.7.0
      - gguf==0.17.1
      - grpcio==1.73.1
      - hjson==3.1.0
      - httptools==0.6.4
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - idna==3.10
      - inquirerpy==0.3.4
      - interegular==0.3.3
      - jinja2==3.1.5
      - joblib==1.4.2
      - lark==1.2.2
      - latex2sympy2-extended==1.10.2
      - liger-kernel==0.6.1
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.12
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - math-verify==0.8.0
      - mdurl==0.1.2
      - mistral-common==1.8.3
      - modelscope==1.28.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - ninja==1.11.1.3
      - num2words==0.5.14
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==13.580.65
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - onnx==1.17.0
      - onnxruntime==1.20.1
      - onnxslim==0.1.59
      - openai==1.90.0
      - opencv-python==4.12.0.88
      - optimum==1.25.0.dev0
      - outlines-core==0.2.10
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post6
      - peft==0.16.0
      - pfzy==0.3.4
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - py-cpuinfo==9.0.0
      - pybase64==1.4.2
      - pycountry==24.6.1
      - pycparser==2.22
      - pydantic-extra-types==2.10.5
      - pydicom==3.0.1
      - pyinstaller==6.14.2
      - pyinstaller-hooks-contrib==2025.8
      - pymysql==1.1.1
      - pyparsing==3.2.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.17
      - pyqt5-sip==12.17.0
      - pysam==0.23.0
      - python-json-logger==3.3.0
      - pytz==2025.1
      - pyyaml==6.0.2
      - ray==2.48.0
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - rich-toolkit==0.15.0
      - rignore==0.6.4
      - safetensors==0.5.2
      - scipy==1.16.1
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.35.0
      - setuptools==79.0.1
      - shellingham==1.5.4
      - sortedcontainers==2.4.0
      - soundfile==0.13.1
      - soupsieve==2.7
      - soxr==0.5.0.post1
      - sqlparse==0.5.3
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tiktoken==0.11.0
      - tokenizers==0.21.0
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - transformers==4.55.0
      - triton==3.3.1
      - trl==0.21.0
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - vllm==0.10.0
      - watchfiles==1.1.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - xformers==0.0.31
      - xgrammar==0.1.21
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /home/tostring/miniconda3/envs/sctranslation
